#!/usr/bin/env python

"""
Example script that prints a human-readable traceroute from a warts file (generated by scamper)
"""

from __future__ import print_function, unicode_literals, division

import sys
from datetime import datetime

import warts


if __name__ == '__main__':
    w = warts.WartsReader(sys.argv[1], verbose=False)
    for (flags, hops) in w.read_all():
        src = flags['srcaddr']
        dest = flags['dstaddr']
        nb_hops = flags['probehop']
        type = warts.TRACEROUTE_TYPE[flags['tracetyp']]
        stop_reason = warts.TRACEROUTE_STOP[flags['stopreas']]
        date = datetime.fromtimestamp(flags['timeval'])
        fmt = "[{}] {} hops from {} to {} (type {}, stop reason {})"
        print(fmt.format(date.strftime("%c"), nb_hops, src, dest,
                         type, stop_reason))
        if len(hops) == 0:
            print()
            continue
        print("{:3} {:27} {:>8} {:>4}".format("Hop", "IP", "RTT", "TTL"))
        hop_id = 1
        for hop in hops:
            # This is necessary to correctly display gaps
            while hop['probettl'] > hop_id:
                print("{:<3}".format(hop_id))
                hop_id += 1
            print("{:<3} {:27} {:>8.3f} {:4}".format(hop_id,
                                                     hop['addr'],
                                                     hop['rtt'] / 1000,
                                                     hop['replyttl']))
            hop_id += 1
        print()
